-- Run this exact SQL command in your Supabase SQL Editor
CREATE TABLE cars (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status text NOT NULL CHECK (status IN ('Available', 'Sold', 'Reserved', 'In Transit')),
  customer_name text,
  chassis_no text UNIQUE NOT NULL,
  price_jpy numeric NOT NULL,
  price_usd numeric NOT NULL,
  port_clearance numeric NOT NULL,
  total_cost_dollars numeric NOT NULL,
  total_cost_shs numeric NOT NULL,
  tax numeric NOT NULL,
  number_plate text,
  vat numeric NOT NULL,
  clearance numeric NOT NULL,
  total_own_cost numeric NOT NULL,
  sold_price numeric,
  profit_shs numeric,
  profit_dollars numeric,
  profit_jpy numeric,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
